### ISSUE TITLE
Cannot import name 'SOM' from partially initialized module 'sompy' 

### ISSUE THREAD

**Issue by dejudicibus** [sevamoo/SOMPY#136]
I get

Traceback (most recent call last):
  File "D:\Projects\AI\SOM\data\sompy_clustering.py", line 1, in <module>
    import sompy
  File "C:\Python\lib\site-packages\sompy\__init__.py", line 2, in <module>
    from sompy import SOM
ImportError: cannot import name 'SOM' from partially initialized module 'sompy' (most likely due to a circular import) (C:\Python\lib\site-packages\sompy\__init__.py)

**Comment by agr17** [comment]
I had the same problem, in my case by installing using `pip install sompy`. Then I realized that this package has nothing to do with this repository. To install this one you have the instructions in the readme, I have not seen that it is available via pip.

**Comment by DanieleGiannuzzi98** [comment]
If you still have problem, try these passages from anaconda cmd (if you use anaconda):
- `pip uninstall sompy`
- `git clone <code link of this library>`
-  `cd_sompy`
-  `python setup.py install`

Then on your notebook you just have to:
- `import sompy`

Probably you already have a version of sompy that is the one that has recursively problems with python>3.0
Therefore, uninstalling sompy and following the right procedures could help. 
Tell me if this is the case! :)
