### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by mohadelrezk** [sevamoo/SOMPY#60]
When installing requirements using setup file `python setup.py install`

this error log appears:

`running install
running bdist_egg
running egg_info
creating SOMPY.egg-info
writing dependency_links to SOMPY.egg-info/dependency_links.txt
writing requirements to SOMPY.egg-info/requires.txt
writing SOMPY.egg-info/PKG-INFO
writing top-level names to SOMPY.egg-info/top_level.txt
writing manifest file 'SOMPY.egg-info/SOURCES.txt'
reading manifest file 'SOMPY.egg-info/SOURCES.txt'
writing manifest file 'SOMPY.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/sompy
copying sompy/decorators.py -> build/lib.linux-x86_64-2.7/sompy
copying sompy/neighborhood.py -> build/lib.linux-x86_64-2.7/sompy
copying sompy/normalization.py -> build/lib.linux-x86_64-2.7/sompy
copying sompy/codebook.py -> build/lib.linux-x86_64-2.7/sompy
copying sompy/__init__.py -> build/lib.linux-x86_64-2.7/sompy
copying sompy/sompy.py -> build/lib.linux-x86_64-2.7/sompy
creating build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/view.py -> build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/hitmap.py -> build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/dotmap.py -> build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/umatrix.py -> build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/mapview.py -> build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/histogram.py -> build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/__init__.py -> build/lib.linux-x86_64-2.7/sompy/visualization
copying sompy/visualization/bmuhits.py -> build/lib.linux-x86_64-2.7/sompy/visualization
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sompy
copying build/lib.linux-x86_64-2.7/sompy/decorators.py -> build/bdist.linux-x86_64/egg/sompy
copying build/lib.linux-x86_64-2.7/sompy/neighborhood.py -> build/bdist.linux-x86_64/egg/sompy
copying build/lib.linux-x86_64-2.7/sompy/normalization.py -> build/bdist.linux-x86_64/egg/sompy
creating build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/view.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/hitmap.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/dotmap.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/umatrix.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/mapview.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/histogram.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/__init__.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/visualization/bmuhits.py -> build/bdist.linux-x86_64/egg/sompy/visualization
copying build/lib.linux-x86_64-2.7/sompy/codebook.py -> build/bdist.linux-x86_64/egg/sompy
copying build/lib.linux-x86_64-2.7/sompy/__init__.py -> build/bdist.linux-x86_64/egg/sompy
copying build/lib.linux-x86_64-2.7/sompy/sompy.py -> build/bdist.linux-x86_64/egg/sompy
byte-compiling build/bdist.linux-x86_64/egg/sompy/decorators.py to decorators.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/neighborhood.py to neighborhood.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/normalization.py to normalization.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/view.py to view.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/hitmap.py to hitmap.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/dotmap.py to dotmap.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/umatrix.py to umatrix.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/mapview.py to mapview.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/histogram.py to histogram.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/visualization/bmuhits.py to bmuhits.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/codebook.py to codebook.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sompy/sompy.py to sompy.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying SOMPY.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SOMPY.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SOMPY.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SOMPY.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SOMPY.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/SOMPY-1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing SOMPY-1.0-py2.7.egg
Copying SOMPY-1.0-py2.7.egg to /home/mohade/workspace/rtpa-SOM/venv/lib/python2.7/site-packages
Adding SOMPY 1.0 to easy-install.pth file

Installed /home/mohade/workspace/rtpa-SOM/venv/lib/python2.7/site-packages/SOMPY-1.0-py2.7.egg
Processing dependencies for SOMPY==1.0
Searching for numexpr>=2.5
Reading https://pypi.python.org/simple/numexpr/
Best match: numexpr 2.6.2
Downloading https://pypi.python.org/packages/31/43/7777ab9535c416faabd1865453389260fdad0a23a714609c13112885009a/numexpr-2.6.2.tar.gz#md5=943f8e4be7569b1ad01b10cbaa002a5c
Processing numexpr-2.6.2.tar.gz
Writing /tmp/easy_install-uatEIX/numexpr-2.6.2/setup.cfg
Running numexpr-2.6.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-uatEIX/numexpr-2.6.2/egg-dist-tmp-YN4_tF
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    'scikit-learn >= 0.16', 'numexpr >= 2.5']
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/install.py", line 97, in do_egg_install
    cmd.run()
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 358, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 574, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 671, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 580, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 818, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 830, in obtain
    return installer(requirement)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 593, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 809, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1015, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1000, in run_setup
    run_setup(setup_script, args)
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/home/mohade/workspace/rtpa-SOM/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 227, in <module>
    
  File "setup.py", line 64, in setup_package
    
ImportError: No module named numpy.distutils.core
`

My solution was creating requirements.txt file containing libraries and install them using `pip install -r  requirements.txt`

**Comment by businessglitch** [comment]
try reinstalling numpy to the latest version
