### ISSUE TITLE
can not import SOM

### ISSUE THREAD

**Issue by azize** [sevamoo/SOMPY#61]
I am using Python 3.5.1 with PyCharm IDE on Windows. I am getting below error:

can you please help me?

C:\Python35\python.exe C:/Users/azzet/PycharmProjects/PythonSom.py
Traceback (most recent call last):
  File "C:/Users/azzet/PycharmProjects/PythonSom.py", line 4, in <module>
    import sompy
  File "C:\Python35\lib\site-packages\sompy\__init__.py", line 2, in <module>
    from sompy import SOM
ImportError: cannot import name 'SOM'

Process finished with exit code 1

**Comment by Nicowhaz** [comment]
I have exactly the same issue

**Comment by honorinli151** [comment]
Me too

**Comment by huqiaoping** [comment]
Me too

**Comment by huqiaoping** [comment]
For those who cannot import sompy, like me, I just create my file in the dir "visualization".  I run the example successfully. But every time when I use it I need to copy those files to my dir again, a bad thing. Anyway , I can use sompy now. thanks to author!

**Comment by sevamoo** [comment]
Sorry, not tested with Py3. with Py2.7 it should work.

**Comment by njali2001** [comment]
Is there any solution for this issue right now?

**Comment by sevamoo** [comment]
@compmonks did you have a solution for this? If I remember correctly you used it in py3?
Thanks

**Comment by compmonks** [comment]
Sompy would not work when loaded as a package for  py 3+ for dependencies and syntax reasons.
@azize @sevamoo , I should have pushed a version for this. Let me know if it works.

**Comment by altermarkive** [comment]
I had the same problem and the SOMPY version forked by @compmonks worked for me:

    pip3 install git+https://github.com/compmonks/SOMPY.git

I only had to remove ipdb import from sompy.py and mapview.py because due to other dependencies I had installed the ipdb import was opening a prompt in my setup.
Thank you @compmonks for the fork!

**Comment by cranzlerdave** [comment]
Have the same issue, but problem appers in my case also in python 2.7. Is there already a solution?

**Comment by riverzhou** [comment]
I have exactly the same issue

**Comment by nomad-jin** [comment]
Same issue. It’s because of ipdb module.Afrer I commented them out in sompy.py and mapview.py, it worked.  It’s just debugger

**Comment by pricklpitty** [comment]
Hi, I have the same issue. What exactly did you comment out? what is 'ipdb'?

**Comment by yangzhili1992** [comment]
how could i save the model , and predict the cluster  of new data , like kmeans in sklearn "model.predict(new_data)"?????????

**Comment by rebelgiri** [comment]
Did anyone found the solution for this open issue?

**Comment by zdvlp** [comment]
I HAVE THE SAME ISSU

**Comment by abdoulsn** [comment]
for me I installed SOMPY using the setup source, this fixed my bug last year. That longtime I've used it.

**Comment by mashirali** [comment]
git clone https://github.com/sevamoo/SOMPY.git
cd SOMPY
python setup.py install

This fixed my issue

**Comment by dejudicibus** [comment]
I get

Traceback (most recent call last):
  File "D:\Projects\AI\SOM\data\sompy_clustering.py", line 3, in <module>
    import sompy as sompy
  File "C:\Python\lib\site-packages\sompy\__init__.py", line 2, in <module>
    from sompy import SOM
ImportError: cannot import name 'SOM' from partially initialized module 'sompy' (most likely due to a circular import) (C:\Python\lib\site-packages\sompy\__init__.py)

Getting the package from GIT does NOT fix the issue. I have Python 3.10.5

**Comment by dimonussir5** [comment]
I get

Traceback (most recent call last):
  File "c:\Users\New\Desktop\clone\som\random_distributions.py", line 2, in <module>
    from som import simom
ImportError: cannot import name 'simom' from 'som' (C:\Program Files\Python312\Lib\s
ite-packages\som\__init__.py)
PS C:\Users\New\Desktop\clone>

**Comment by CarolinaGoncalinho** [comment]
I have the same issue. How did you solve it?
