### ISSUE TITLE
Tuple index out of range 

### ISSUE THREAD

**Issue by BuiltForThis** [sevamoo/SOMPY#78]
My goal is to enter binary vector data (vectors are each 16 values long) and extract the som, and label every piece of enetered data as well as name the clusters. 
I entered the data without names, because I don't know how SOM would respond to strings.
```
import matplotlib.pylab as plt  # The imports
import numpy as np
from time import time
import sompy
import pandas as pd

data = open('verbsnumbers.csv', 'rt', encoding='cp1252')  # The data
data = data.read() 
data = data.replace(';','')  # this deletes all semicolons. Data seems to be read correctly and can be printed as an array of binary vectors

mapsize = [10,10]  # The SOM
som = sompy.SOMFactory.build(data, mapsize, mask=None, mapshape='planar', lattice='rect', initialization='pca', training='batch', name='sompy')  # This line causes an error. Should I change initialization or neighborhood methods? To what?
```
Here is the traceback: 
Traceback (most recent call last):
  File "D:/Anže/PycharmProjects/Self Organizing Map/SOM.py", line 54, in <module>
    som = sompy.SOMFactory.build(data, mapsize, mask=None, mapshape='planar', lattice='rect', initialization='pca', training='batch', name='sompy') 
  File "D:\Anže\Python_Bratislava\lib\site-packages\sompy\sompy.py", line 96, in build
    mapshape, lattice, initialization, training, name, component_names)
  File "D:\Anže\Python_Bratislava\lib\site-packages\sompy\sompy.py", line 129, in __init__
    self._data = normalizer.normalize(data) if normalizer else data
  File "D:\Anže\Python_Bratislava\lib\site-packages\sompy\normalization.py", line 38, in normalize
    me, st = self._mean_and_standard_dev(data)
  File "D:\Anže\Python_Bratislava\lib\site-packages\sompy\normalization.py", line 35, in _mean_and_standard_dev
    return np.mean(data, axis=0), np.std(data, axis=0)
  File "D:\Anže\Python_Bratislava\lib\site-packages\numpy\core\fromnumeric.py", line 2909, in mean
    out=out, **kwargs)
  File "D:\Anže\Python_Bratislava\lib\site-packages\numpy\core\_methods.py", line 57, in _mean
    rcount = _count_reduce_items(arr, axis)
  File "D:\Anže\Python_Bratislava\lib\site-packages\numpy\core\_methods.py", line 50, in _count_reduce_items
    items *= arr.shape[ax]
IndexError: tuple index out of range

Data files:
[verbs.xlsx](https://github.com/sevamoo/SOMPY/files/1865546/verbs.xlsx)
[verbsnumbers.xlsx](https://github.com/sevamoo/SOMPY/files/1865548/verbsnumbers.xlsx) <= The actual training data, except the data I used is in .csv form.

**Comment by BuiltForThis** [comment]
I've printed out the contents of the line where the error occours.
ax = 0 
axis = (0,) 
arr.shape: ()
the array is not a tuple. 

Then this piece of code occurs: 
items *= arr.shape[ax]
where items = 1
Thus: 
1 *= ()[0]
It tries to multiply with the first item of an empty tuple... -_-' 

Any hints on what to do? I'm thinking about packing data into a list of tuples, but I am hesitant because until now the only thing the SOM has processed was a numpy array.
